### ISSUE TITLE
JsInterop javadoc

### ISSUE THREAD

**Issue by tbroyer** [gwtproject/gwt-site#337]
I just stumbled upon https://www.gwtproject.org/javadoc/latest/jsinterop/annotations/package-summary.html which is still 2.9.0 and should have been removed by this #331.

This is linked from https://www.gwtproject.org/doc/latest/DevGuideCodingBasicsJsInterop.html which should now point to https://javadoc.io/doc/com.google.jsinterop/jsinterop-annotations/latest/index.html

**Comment by niloc132** [comment]
DevGuideCodingBasicsJsInterop.md still reference these - this was not deliberate on my part to keep these docs around, just an observation as I try to remove them.

Probably we want to have another place to host jsinterop-annotations javadocs, likely on gwtproject.org, since Google doesn't host them.

I'd also like to consider assembling the build output by unpacking the GWT sdk zip itself rather than checking in generated files like this, unless anyone has an objection there?
